"""Langfuse tracing — the AI-plane observability seam.

The ONLY module that imports the Langfuse SDK (v4, OTel-based). Everything is
defensive: tracing must never break a request. If keys are missing or the
server is unreachable, the tracer runs disabled and every call is a no-op.

ID mapping (the join key design):
    Langfuse trace id  <- generated by the conversation root observation
    Langfuse root      <- persisted conversation observation id
  Langfuse user      <- user_id
  metadata           <- role, login session (jti)
Message observations attach to the persisted root; their children nest via OTel.
"""
from contextlib import contextmanager
from contextvars import ContextVar
from functools import lru_cache
import logging
from typing import Any

from app.config import get_settings

logger = logging.getLogger("insureagent.tracing")


class Tracer:
    def __init__(self):
        self._client = None
        self._request_trace_active = ContextVar(
            f"request_trace_active_{id(self)}", default=False
        )
        s = get_settings()
        if not (s.langfuse_public_key and s.langfuse_secret_key):
            logger.info("tracing disabled (no Langfuse keys configured)")
            return
        try:
            from langfuse import Langfuse

            client = Langfuse(
                public_key=s.langfuse_public_key,
                secret_key=s.langfuse_secret_key,
                host=s.langfuse_base_url or "http://localhost:3000",
            )
            if not client.auth_check():
                logger.warning("tracing disabled (Langfuse auth check failed)")
                return
            self._client = client
            logger.info("tracing enabled -> %s", s.langfuse_base_url)
        except Exception as exc:  # unreachable server, bad config, SDK drift
            logger.warning("tracing disabled (%s: %s)", type(exc).__name__, exc)

    @property
    def enabled(self) -> bool:
        return self._client is not None

    def legacy_request_trace_id(self, correlation_id: str) -> str | None:
        """Resolve trace IDs created before conversation-level tracing."""
        if not self._client:
            return None
        return self._client.create_trace_id(seed=correlation_id)

    def create_conversation_trace(self, ctx, conversation_id: str):
        """Create a native root observation and return its persisted IDs."""
        if not self._client:
            return None
        try:
            from langfuse import propagate_attributes

            attrs_cm = propagate_attributes(
                user_id=ctx.user.user_id,
                session_id=conversation_id,
                tags=[ctx.user.role.value],
                metadata={
                    "conversation_id": conversation_id,
                    "login_session": ctx.session_id or "",
                },
            )
            span_cm = self._client.start_as_current_observation(
                name="conversation",
                as_type="span",
            )
            with attrs_cm, span_cm as span:
                context = (span.trace_id, span.id)
        except Exception:
            logger.exception("failed to create conversation trace")
            return None
        finally:
            self.flush()
        return context

    @contextmanager
    def request_trace(
        self,
        ctx,
        user_input: str | None = None,
        *,
        trace_id: str | None = None,
        parent_span_id: str | None = None,
    ):
        """Wrap one message turn beneath its persisted conversation observation."""
        if not self._client:
            yield None
            return
        if self._request_trace_active.get():
            yield None
            return
        try:
            from langfuse import propagate_attributes

            trace_id = trace_id or self._client.create_trace_id(
                seed=f"conversation:{ctx.conversation_id}"
                if ctx.conversation_id else ctx.correlation_id
            )
            trace_context = {"trace_id": trace_id}
            if parent_span_id:
                trace_context["parent_span_id"] = parent_span_id
            attrs_cm = propagate_attributes(
                user_id=ctx.user.user_id,
                session_id=ctx.conversation_id or ctx.correlation_id,
                tags=[ctx.user.role.value],
                metadata={
                    "correlation_id": ctx.correlation_id,
                    "login_session": ctx.session_id or "",
                },
            )
            span_cm = self._client.start_as_current_observation(
                name="chat_request",
                as_type="span",
                input=user_input,
                trace_context=trace_context,
            )
        except Exception:
            logger.exception("failed to open trace")
            yield None
            return
        try:
            with attrs_cm, span_cm as span:
                token = self._request_trace_active.set(True)
                try:
                    yield span
                finally:
                    self._request_trace_active.reset(token)
        finally:
            self.flush()

    def update_request_input(self, span, user_input: str) -> None:
        """Record the guardrail-processed input on the turn observation."""
        if span:
            try:
                span.update(input=user_input)
            except Exception:
                logger.exception("failed to update request input")

    @contextmanager
    def observation(self, name: str, *, input: Any = None, metadata: dict | None = None):
        """Create a child observation while preserving the active trace context."""
        if not self._client:
            yield None
            return
        try:
            observation = self._client.start_as_current_observation(
                name=name,
                as_type="span",
                input=input,
                metadata=metadata or {},
            )
        except Exception:
            logger.exception("failed to open observation %s", name)
            yield None
            return
        with observation as span:
            try:
                yield span
            except Exception as exc:
                try:
                    span.update(level="ERROR", status_message=str(exc))
                except Exception:
                    logger.exception("failed to mark observation %s", name)
                raise

    def log_route(self, *, next_agent: str, outcome: str | None, state: dict) -> None:
        """Record the deterministic routing decision made after the supervisor."""
        with self.observation(
            "graph:routing",
            input={"next_agent": next_agent, "outcome": outcome},
            metadata={"state_keys": sorted(state)},
        ) as span:
            if span:
                span.update(output={"next_agent": next_agent, "outcome": outcome})

    def log_rag_retrieval(
        self, *, query: str, collection: str, results: dict, output: list[dict]
    ) -> None:
        """Record the ranked vector-search evidence used for an FAQ answer."""
        documents = (results.get("documents") or [[]])[0]
        ids = (results.get("ids") or [[]])[0]
        distances = (results.get("distances") or [[]])[0]
        metadatas = (results.get("metadatas") or [[]])[0]
        ranked = [
            {
                "rank": index + 1,
                "id": ids[index] if index < len(ids) else None,
                "distance": distances[index] if index < len(distances) else None,
                "document": documents[index] if index < len(documents) else None,
                "metadata": metadatas[index] if index < len(metadatas) else {},
            }
            for index in range(max(len(documents), len(ids)))
        ]
        with self.observation(
            "rag:faq_retrieval",
            input={"query": query, "collection": collection, "top_k": len(output)},
            metadata={"result_count": len(output)},
        ) as span:
            if span:
                span.update(output={"ranked_results": ranked, "context": output})

    def log_generation(
        self, *, agent: str, model: str, tier: str,
        messages: list, output: Any, input_tokens: int, output_tokens: int,
    ) -> None:
        if not self._client:
            return
        try:
            # Use start_as_current_observation to nest under the active request trace
            with self._client.start_as_current_observation(
                name=f"llm:{agent}", as_type="generation",
                input=messages, model=model, metadata={"tier": tier},
            ) as generation:
                generation.update(
                    output=output,
                    usage_details={"input": input_tokens, "output": output_tokens},
                )
        except Exception:
            logger.exception("failed to log generation")

    def log_guardrail(
        self, *, check: str, action: str, reason: str,
        scores: dict | None = None, mode: str = "enforce",
    ) -> None:
        if not self._client:
            return
        try:
            # Use start_as_current_observation for proper nesting
            with self._client.start_as_current_observation(
                name=f"guardrail:{check}", as_type="span",
                input={"mode": mode},
                metadata={"action": action, "reason": reason},
            ) as span:
                span.update(
                    output={"action": action, "scores": scores or {}},
                    level="WARNING" if action in ("block", "escalate") else "DEFAULT",
                )
        except Exception:
            logger.exception("failed to log guardrail verdict")

    def log_tool_call(self, *, name: str, args: dict, ok: bool, output: Any) -> None:
        if not self._client:
            return
        try:
            # Use start_as_current_observation to ensure nesting under request trace
            with self._client.start_as_current_observation(
                name=f"tool:{name}", as_type="span",
                input=args, metadata={"ok": ok},
            ) as span:
                span.update(output=output, level="ERROR" if not ok else "DEFAULT")
        except Exception:
            logger.exception("failed to log tool call")

    def log_state(self, *, node: str, state: dict) -> None:
        """Record the full graph state after a node execution for deep tracing."""
        if not self._client:
            return
        try:
            with self._client.start_as_current_observation(
                name=f"state:{node}", as_type="span",
                input=state,
                metadata={"node": node},
            ):
                pass
        except Exception:
            logger.exception("failed to log state for node %s", node)


    def finish_request(self, outcome: str, answer: str) -> None:
        """Annotate the current trace with the final result."""
        if not self._client:
            return
        try:
            self._client.update_current_span(output={"outcome": outcome, "answer": answer})
        except Exception:
            logger.exception("failed to finish trace")

    def score(
        self,
        trace_id: str,
        name: str,
        value: float,
        comment: str | None = None,
        idempotency_key: str | None = None,
        observation_id: str | None = None,
    ) -> None:
        """Attach feedback to a trace or a specific message observation.

        idempotency_key (e.g. the message_id) makes repeat submissions
        OVERWRITE the same score instead of stacking duplicates."""
        if not self._client:
            return
        try:
            score_id = (
                self._client.create_trace_id(seed=f"score:{name}:{idempotency_key}")
                if idempotency_key else None
            )
            self._client.create_score(
                trace_id=trace_id, name=name, value=value,
                observation_id=observation_id,
                comment=comment, score_id=score_id,
            )
            self._client.flush()
        except Exception:
            logger.exception("failed to score trace")

    def flush(self) -> None:
        if self._client:
            try:
                self._client.flush()
            except Exception:
                logger.exception("flush failed")


@lru_cache
def get_tracer() -> Tracer:
    return Tracer()
